language: java
jdk: openjdk11 # Replace with your required JDK version
before_install:
  - chmod +x mvnw
  # Add commands here to install a specific Maven version if necessary
script: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
